### ISSUE TITLE
injected dependencies in @QueueProcess are undefined

### ISSUE THREAD

**Issue by anitricks** [nestjsx/nest-bull#159]
a weird issue that i cannot solve. The UsersModule is imported in the AppModule. The BullModule is imported within the UsersModule, with the UsersQueue and UserService declared as providers. However, every time the job is added and processed the processor named 'update' throws a error saying that the service is not defined. I cannot even access the logger property inside the queue. So im thinking it is a scope problem.

NestJS version: 6.5.2
nest-bull: 0.8.2

**UsersModule**
```
@Module({
  imports: [
    BullModule.forRoot({
      name: 'users',
      options: {
        redis: {
          port: 0000
        }
      }
    }),
  ],
  providers: [
    UsersService,
    UsersQueue
  ],
  controllers: [UsersController],
  exports: [UsersService]
})
```

**UsersService**
```
@Injectable()
export class UsersService extends Entity<User> {

    constructor(
        @InjectRepository(User) repo: Repository<User>,
        connection: Connection
    ) {
        super(repo, connection);
    }

    findUsers(params: { firstname?: string, lastname?: string, dob?: string }) {
        //
    }
}
```

**UsersQueue**
```
@Queue({name: 'users'})
export class UsersQueue {

    private readonly logger = new Logger(this.constructor.name);
    constructor(private readonly service: UsersService) { }

    @QueueProcess({name: 'update'})
    async defaultFunction(job: Job) {
        console.log(this);
        let res = await this.service.findUsers({id: job.data});
        return done(null, res);
    }
```

**Comment by fwoelffel** [comment]
What's the output of `console.log(this)` in your `defaultFunction`?

**Comment by anitricks** [comment]
```
UsersQueue {}
```

**Comment by nartc** [comment]
the `queueName` does not match. Are you sure that it's correct or it's a typo?

**Comment by anitricks** [comment]
@nartc yeah sorry it was a typo. i would have gotten an error otherwise but there isn't any error.

**Comment by anitricks** [comment]
@nartc @fwoelffel So I created another temp service from the nest-bull example without any dependencies injected in the constructor. The problem is occurring on the UsersService. if the service is not injected without any dependencies in the constructor the UsersQueue works fine. The UsersService has the repo connection to the User entity so I cannot remove it from the service. Any suggestions how to fix this?

**Comment by fwoelffel** [comment]
Could you create a small repository reproducing this issue? I don't have much time to do it myself.

**Comment by anitricks** [comment]
@fwoelffel yeah sure. I will create a sample repo

**Comment by anitricks** [comment]
@fwoelffel thanks for the help but i figured it out. Turns out the service i was injecting into the queue had a dependency of another service with a scope of the request. ```@Injectable({ scope: Scope.REQUEST})``` thus the whole service didn't inject into the queue. 

just started out with NestJs so it took time to find it lol. sorry for any trouble caused

**Comment by fwoelffel** [comment]
I guess this usecase might cause some trouble anytime soon. Sadly, I haven't worked with the injection scopes yet... IMO, this has something to do with the actual Bull queue being bound to the service at the module's injection (which, I believe is injected once despite any request scope) and not at the service's injection. Not sure about that though.
Anyway, thanks for your feedback :slightly_smiling_face:
