### ISSUE TITLE
Examples using multiples Queue

### ISSUE THREAD

**Issue by focux** [nestjsx/nest-bull#163]
I'm running into some issues when trying to use multiples queues, maybe are not issues but misunderstanding due to the lack of examples.

So, I'm importing this in my app module:

```typescript
BullModule.forRoot([
      {
        name: 'push',
        options: {
          redis: {
            host: 'x-redis',
            port: 6379,
          },
        },
      },
      {
        name: 'email',
        options: {
          redis: {
            host: 'x-redis',
            port: 6379,
          },
        },
      },
      {
        name: 'cron',
        options: {
          redis: {
            host: 'x-redis',
            port: 6379,
          },
        },
      },
    ])
```

All my queues (processes) run fine doing only that, the problem comes when trying to inject a queue, e.g.

```typescript
@Module({
  imports: [ConfigModule],
  providers: [CronQueue],
})
export class CronModule implements OnModuleInit {
  constructor(@InjectQueue('cron') private readonly cronQueue: Queue) {}

  async onModuleInit() {
    await this.cronQueue.add('checkFreeTrialEligibility', true, {
      repeat: { cron: '01 13 * * *' },
    });
  }
}
```

The error I get is that Nest can't resolve the injected queue dependency.

**Nest-bull:**  v0.6.2
**Nest:** v6.0
**Node**: v10.15.1

**Comment by fwoelffel** [comment]
Hi @focux!
Isn't this related to #110?

**Comment by focux** [comment]
It worked, thank you for your help. Also, maybe it'd be good if that info it's added to the readme.

**Comment by fwoelffel** [comment]
Could I recommend you to upgrade `nest-bull` to v0.8.4? `forRoot` and `forRootAsync` have been deprecated in favor of `register` and `registerAsync`. This may help avoid further confusion. No breaking changes (`forRoot` and `forRootAsync` are still there for the moment but you'll see a warning).
