### ISSUE TITLE
Handle specified Job Event 

### ISSUE THREAD

**Issue by callmez** [nestjsx/nest-bull#165]
Hi @fwoelffel , it would be nice if we can handle specified job event by job name or ID. 

```js
import {
  Processor,
  Process,
  OnQueueFailed,
  OnGlobalQueueFailed,
} from 'nest-bull';

import { Job } from 'bull';

@Processor({ name: 'default_queue' })
export class TestQueue {
  @Process({ name: 'test' })
  processTest(job: Job) {}

  @OnQueueFailed({ name: 'test' })
  onTestError() {}
  // ...

  @OnGlobalQueueFailed()
  onGlobalError() {}
}

```

**Comment by fwoelffel** [comment]
Hi @callmez 

Unfortunately this feature isn't shipped with [bull](https://github.com/OptimalBits/bull). However, I believe it can be achieved by changing https://github.com/nestjsx/nest-bull/blob/dev/lib/bull.explorer.ts#L81
I haven't thought about performance implications, so we should be cautious with this.

Feel free to submit a PR. I currently don't have the time to work on this feature but it might also be useful to others.
