### ISSUE TITLE
Cron Processor

### ISSUE THREAD

**Issue by jphgardner02** [nestjsx/nest-bull#168]
Hi,

I am looking at using this library to allow my application to support background jobs.

Some jobs will be added to the Queue and others will need to be ran on a Cron Specification.

At the moment i am struggling to correctly configure a Cron Process.

`@Processor({ name: 'store' })
export class ScheduleService {

	constructor(private readonly _http: HttpService,
				private readonly _connectionManager: ConnectionManagerService,
				private readonly _sanctionService: SanctionsService) {
	}

	@Process({ name: 'importSanctionList' })
	/*@Cron('59 23 * * *', {
		enable: true,
		key: 'importSanctionList',
		startTime: new Date(),
		// immediate: true
		// endTime: new Date(new Date().getTime() + 24 * 60 * 60 * 1000),
	})*/
	async importSanctionList() {
		console.log("Run importSanctionList");
	}

	private _parseXML(xml) : Promise<any> {
		return xml2js.parseStringPromise(xml, {
			ignoreAttrs: true,
			trim: true,
			explicitArray: false,
			normalizeTags: true
		});
	}

	@OnQueueActive()
	onActive(job: Job) {
		console.log(
			`Processing job ${job.id} of type ${job.name} with data ${job.data}...`,
		);
	}

	@OnQueueEvent(BullQueueEvents.COMPLETED)
	onCompleted(job: Job) {
		console.log(
			`Completed job ${job.id} of type ${job.name} with result ${job.returnvalue}`,
		);
	}

}`

I need the importSanctionList function to run at midnight every day.

**Comment by fwoelffel** [comment]
Hi @jphgardner02 
You could try to add a repeatable job in your queue. See https://optimalbits.github.io/bull#repeatable

**Comment by jphgardner02** [comment]
@fwoelffel Is there a way to add this to the @Process Decorator, or would i have to add a repeatable job everytime nestjs starts?

**Comment by fwoelffel** [comment]
I haven't tried this myself, but I guess you would have to add the repeatable job everytime NestJS starts. According to Bull's documentation, the library is smart enough not to add/process the same repeatable job multiple times.
